# Generated by Django 4.2.7 on 2023-11-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Y_ISH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomzod', models.CharField(max_length=200)),
                ('pdf_ish', models.FileField(upload_to=None)),
            ],
        ),
    ]
