# Generated by Django 4.2.6 on 2023-12-01 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='y_ish',
            name='pdf_ish',
            field=models.FileField(upload_to='pdf/'),
        ),
    ]
